# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The TechGlider
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning and sharing about Computer Science, programming, research & technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techglider.github.io" # the base hostname & protocol for your site
twitter_username: TechGlider
github_username:  TechGlider

# Build settings
markdown: kramdown
